from datetime import (
    datetime,
    timezone,
)

from fake_test_session_api.schemas import (
    TestSession,
    TestSessionStatus,
    TestType,
)


TEST_SESSIONS = [
    TestSession(
        id="SESSION-SAFI-001",
        campus="Safi",
        test_type=TestType.IN_PERSON,
        start_at=datetime(
            2026,
            8,
            5,
            9,
            0,
            tzinfo=timezone.utc,
        ),
        capacity=30,
        registered_candidates=30,
        status=TestSessionStatus.FULL,
    ),
    TestSession(
        id="SESSION-SAFI-002",
        campus="Safi",
        test_type=TestType.IN_PERSON,
        start_at=datetime(
            2026,
            8,
            12,
            9,
            0,
            tzinfo=timezone.utc,
        ),
        capacity=30,
        registered_candidates=25,
        status=TestSessionStatus.OPEN,
    ),
    TestSession(
        id="SESSION-SAFI-003",
        campus="Safi",
        test_type=TestType.IN_PERSON,
        start_at=datetime(
            2026,
            8,
            20,
            14,
            0,
            tzinfo=timezone.utc,
        ),
        capacity=30,
        registered_candidates=10,
        status=TestSessionStatus.OPEN,
    ),
    TestSession(
        id="SESSION-YOUSSOUFIA-001",
        campus="Youssoufia",
        test_type=TestType.IN_PERSON,
        start_at=datetime(
            2026,
            8,
            15,
            9,
            0,
            tzinfo=timezone.utc,
        ),
        capacity=40,
        registered_candidates=18,
        status=TestSessionStatus.OPEN,
    ),
    TestSession(
        id="SESSION-NADOR-001",
        campus="Nador",
        test_type=TestType.IN_PERSON,
        start_at=datetime(
            2026,
            8,
            18,
            9,
            0,
            tzinfo=timezone.utc,
        ),
        capacity=25,
        registered_candidates=5,
        status=TestSessionStatus.OPEN,
    ),
    TestSession(
        id="SESSION-NADOR-002",
        campus="Nador",
        test_type=TestType.IN_PERSON,
        start_at=datetime(
            2026,
            8,
            25,
            9,
            0,
            tzinfo=timezone.utc,
        ),
        capacity=25,
        registered_candidates=0,
        status=(
            TestSessionStatus.CANCELLED
        ),
    ),
]