apiVersion: apps/v1
kind: Deployment
metadata:
  name: evolution-api
  labels:
    app: evolution-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evolution-api
  template:
    metadata:
      labels:
        app: evolution-api
    spec:
      containers:
      - name: evolution-api
        image: "{{ .Values.evolution.image.repository }}:{{ .Values.evolution.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_URL
          value: "http://localhost:8080"
        - name: CORS_ORIGIN
          value: "*"
        - name: DATABASE_PROVIDER
          value: "postgresql"
        - name: DATABASE_CONNECTION_URI
          value: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@postgres:5432/{{ .Values.postgres.auth.database }}"
        - name: REDIS_URI
          value: "redis://redis:6379/1"
        - name: CACHE_REDIS_URI
          value: "redis://redis:6379/2"
        - name: RABBITMQ_ENABLED
          value: "false"
        - name: AUTHENTICATION_API_KEY
          value: "B6D711FCDE4D4FD5936544120E713976"
        - name: AUTHENTICATION_EXPOSE_IN_ENV
          value: "true"
        - name: WEBHOOK_GLOBAL_URL
          value: "{{ .Values.evolution.env.webhook_global_url }}"
        - name: WEBHOOK_GLOBAL_ENABLED
          value: "true"
        - name: WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS
          value: "false"
        - name: WEBHOOK_EVENTS_APPLICATION_STARTUP
          value: "false"
        - name: WEBHOOK_EVENTS_QRCODE_UPDATED
          value: "true"
        - name: WEBHOOK_EVENTS_MESSAGES_SET
          value: "true"
        - name: WEBHOOK_EVENTS_MESSAGES_UPSERT
          value: "true"
        - name: WEBHOOK_EVENTS_MESSAGES_UPDATE
          value: "true"
        - name: WEBHOOK_EVENTS_MESSAGES_DELETE
          value: "false"
        - name: WEBHOOK_EVENTS_SEND_MESSAGE
          value: "true"
        - name: WEBHOOK_EVENTS_CONTACTS_SET
          value: "true"
        - name: WEBHOOK_EVENTS_CONTACTS_UPSERT
          value: "true"
        - name: WEBHOOK_EVENTS_CONTACTS_UPDATE
          value: "true"
        - name: WEBHOOK_EVENTS_PRESENCE_UPDATE
          value: "false"
        - name: WEBHOOK_EVENTS_CHATS_SET
          value: "true"
        - name: WEBHOOK_EVENTS_CHATS_UPSERT
          value: "true"
        - name: WEBHOOK_EVENTS_CHATS_UPDATE
          value: "true"
        - name: WEBHOOK_EVENTS_CHATS_DELETE
          value: "false"
        - name: WEBHOOK_EVENTS_GROUPS_UPSERT
          value: "true"
        - name: WEBHOOK_EVENTS_GROUP_UPDATE
          value: "true"
        - name: WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE
          value: "true"
        - name: WEBHOOK_EVENTS_CONNECTION_UPDATE
          value: "true"
        - name: WEBHOOK_EVENTS_CALL
          value: "true"
        resources:
          requests:
            cpu: "{{ .Values.evolution.resources.requests.cpu }}"
            memory: "{{ .Values.evolution.resources.requests.memory }}"
        volumeMounts:
        - name: evolution-instances
          mountPath: /evolution/instances
      volumes:
      - name: evolution-instances
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: evolution-api
spec:
  selector:
    app: evolution-api
  ports:
  - port: 8080
    targetPort: 8080
