apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.microservices.gateway.image.repository }}:{{ .Values.microservices.gateway.image.tag }}"
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@postgres:5432/{{ .Values.postgres.auth.database }}"
        - name: ORCHESTRATOR_URL
          value: "http://orchestrator:8006"
        - name: AUTH_SECRET_KEY
          value: "{{ .Values.evolution.env.auth_jwt_secret }}"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
  - port: 8000
    targetPort: 8000
