apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsletter
  labels:
    app: newsletter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsletter
  template:
    metadata:
      labels:
        app: newsletter
    spec:
      containers:
      - name: newsletter
        image: "{{ .Values.microservices.newsletter.image.repository }}:{{ .Values.microservices.newsletter.image.tag }}"
        ports:
        - containerPort: 8003
        env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@postgres:5432/{{ .Values.postgres.auth.database }}"
        - name: SHEET_GMCP_URL
          value: "http://sheet-gmcp:8004"
        envFrom:
        - secretRef:
            name: youcode-secrets
            optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: newsletter
spec:
  selector:
    app: newsletter
  ports:
  - port: 8003
    targetPort: 8003
