"""add identity fields to visitor request and newsletter

Revision ID: 4232efa12081
Revises: e61e6a8050dc
Create Date: 2026-07-25 11:18:17.173920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4232efa12081'
down_revision: Union[str, Sequence[str], None] = 'e61e6a8050dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('cin', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_newsletter_subscriptions_cin'), ['cin'], unique=False)
        batch_op.create_index(batch_op.f('ix_newsletter_subscriptions_phone_number'), ['phone_number'], unique=False)

    with op.batch_alter_table('visitor_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('cin', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_visitor_requests_cin'), ['cin'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_requests_phone_number'), ['phone_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_requests_phone_number'))
        batch_op.drop_index(batch_op.f('ix_visitor_requests_cin'))
        batch_op.drop_column('cin')
        batch_op.drop_column('full_name')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('newsletter_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_subscriptions_phone_number'))
        batch_op.drop_index(batch_op.f('ix_newsletter_subscriptions_cin'))
        batch_op.drop_column('cin')
        batch_op.drop_column('full_name')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
