"""add_newsletter_campaigns_and_campus

Revision ID: 4c6ab0d6e61a
Revises: a8b5f9f94168
Create Date: 2026-07-22 21:42:29.012514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6ab0d6e61a'
down_revision: Union[str, Sequence[str], None] = 'a8b5f9f94168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('target_topics', sa.Text(), nullable=True),
    sa.Column('target_campuses', sa.Text(), nullable=True),
    sa.Column('target_languages', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'sending', 'completed', 'cancelled', 'failed', name='campaignstatus', native_enum=False, length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_campaigns'))
    )
    with op.batch_alter_table('newsletter_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_campaigns_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_newsletter_campaigns_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'support', 'newsletter_manager', name='userrole', native_enum=False, length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('newsletter_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_newsletter_subscriptions_campus'), ['campus'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_subscriptions_campus'))
        batch_op.drop_column('campus')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('newsletter_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_newsletter_campaigns_reference'))

    op.drop_table('newsletter_campaigns')
    # ### end Alembic commands ###
