"""extend_email_deliveries_add_outbox_columns

Revision ID: a8b5f9f94168
Revises: 71e5422af370
Create Date: 2026-07-22 21:38:24.842924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b5f9f94168'
down_revision: Union[str, Sequence[str], None] = '71e5422af370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payload_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('visitor_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_requests', schema=None) as batch_op:
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('review_note')

    with op.batch_alter_table('email_deliveries', schema=None) as batch_op:
        batch_op.drop_column('scheduled_at')
        batch_op.drop_column('attempts')
        batch_op.drop_column('payload_json')
        batch_op.drop_column('template_name')

    # ### end Alembic commands ###
