"""create initial tables

Revision ID: cb6bcad2b7e7
Revises: 
Create Date: 2026-07-22 00:04:37.716831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6bcad2b7e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.Enum('support_request', 'newsletter', name='consentpurpose', native_enum=False, length=50), nullable=False),
    sa.Column('subject_hash', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('consent_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_grants'))
    )
    with op.batch_alter_table('consent_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_grants_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_grants_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_consent_grants_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_grants_subject_hash'), ['subject_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_grants_token_hash'), ['token_hash'], unique=True)

    op.create_table('knowledge_gaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_question', sa.Text(), nullable=False),
    sa.Column('normalized_question', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('general', 'admission', 'program', 'campus', 'pedagogy', 'career', 'event', 'practical', name='knowledgecategory', native_enum=False, length=50), nullable=False),
    sa.Column('language', sa.Enum('fr', 'en', 'ar', 'darija', name='language', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_review', 'resolved', 'rejected', name='knowledgegapstatus', native_enum=False, length=30), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('vector_point_id', sa.String(length=100), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_gaps')),
    sa.UniqueConstraint('vector_point_id', name=op.f('uq_knowledge_gaps_vector_point_id'))
    )
    with op.batch_alter_table('knowledge_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_gaps_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_gaps_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_gaps_normalized_question'), ['normalized_question'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_gaps_status'), ['status'], unique=False)

    op.create_table('knowledge_gap_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gap_id', sa.String(length=36), nullable=False),
    sa.Column('raw_answer', sa.Text(), nullable=False),
    sa.Column('structured_answer', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'published', 'rejected', name='knowledgeanswerstatus', native_enum=False, length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gap_id'], ['knowledge_gaps.id'], name=op.f('fk_knowledge_gap_answers_gap_id_knowledge_gaps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_gap_answers'))
    )
    with op.batch_alter_table('knowledge_gap_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_gap_answers_gap_id'), ['gap_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_gap_answers_status'), ['status'], unique=False)

    op.create_table('knowledge_gap_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gap_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=True),
    sa.Column('original_question', sa.Text(), nullable=False),
    sa.Column('normalized_question', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('fr', 'en', 'ar', 'darija', name='language', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gap_id'], ['knowledge_gaps.id'], name=op.f('fk_knowledge_gap_questions_gap_id_knowledge_gaps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_gap_questions'))
    )
    with op.batch_alter_table('knowledge_gap_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_gap_questions_gap_id'), ['gap_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_gap_questions_session_id'), ['session_id'], unique=False)

    op.create_table('newsletter_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('language', sa.Enum('fr', 'en', 'ar', 'darija', name='language', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('active', 'unsubscribed', 'blocked', name='subscriptionstatus', native_enum=False, length=30), nullable=False),
    sa.Column('consent_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consent_id'], ['consent_grants.id'], name=op.f('fk_newsletter_subscriptions_consent_id_consent_grants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_subscriptions'))
    )
    with op.batch_alter_table('newsletter_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_subscriptions_consent_id'), ['consent_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_newsletter_subscriptions_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_newsletter_subscriptions_status'), ['status'], unique=False)

    op.create_table('visitor_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('request_type', sa.Enum('test_reschedule', 'platform_access', 'login_problem', 'application_problem', 'other_support', name='requesttype', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'pending_approval', 'approved', 'rejected', 'escalated', 'completed', 'cancelled', name='requeststatus', native_enum=False, length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('language', sa.Enum('fr', 'en', 'ar', 'darija', name='language', native_enum=False, length=20), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_test_date', sa.Date(), nullable=True),
    sa.Column('requested_test_date', sa.Date(), nullable=True),
    sa.Column('external_session_id', sa.String(length=100), nullable=True),
    sa.Column('proposed_test_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['consent_grants.id'], name=op.f('fk_visitor_requests_consent_id_consent_grants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitor_requests'))
    )
    with op.batch_alter_table('visitor_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_requests_campus'), ['campus'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_requests_consent_id'), ['consent_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_visitor_requests_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_requests_external_session_id'), ['external_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_requests_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_visitor_requests_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_requests_status'), ['status'], unique=False)

    op.create_table('email_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_email', sa.String(length=320), nullable=False),
    sa.Column('email_type', sa.Enum('subscription_confirmation', 'newsletter', 'unsubscribe_confirmation', name='emailtype', native_enum=False, length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='emaildeliverystatus', native_enum=False, length=30), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['newsletter_subscriptions.id'], name=op.f('fk_email_deliveries_subscription_id_newsletter_subscriptions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_deliveries'))
    )
    with op.batch_alter_table('email_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_deliveries_email_type'), ['email_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_provider_message_id'), ['provider_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_recipient_email'), ['recipient_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('newsletter_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.Enum('full_program_registration', 'bootcamps', 'events', name='newslettertopic', native_enum=False, length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['newsletter_subscriptions.id'], name=op.f('fk_newsletter_preferences_subscription_id_newsletter_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_preferences')),
    sa.UniqueConstraint('subscription_id', 'topic', name='uq_newsletter_subscription_topic')
    )
    with op.batch_alter_table('newsletter_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_preferences_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_newsletter_preferences_topic'), ['topic'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_preferences_topic'))
        batch_op.drop_index(batch_op.f('ix_newsletter_preferences_subscription_id'))

    op.drop_table('newsletter_preferences')
    with op.batch_alter_table('email_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_deliveries_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_recipient_email'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_provider_message_id'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_email_type'))

    op.drop_table('email_deliveries')
    with op.batch_alter_table('visitor_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_requests_status'))
        batch_op.drop_index(batch_op.f('ix_visitor_requests_request_type'))
        batch_op.drop_index(batch_op.f('ix_visitor_requests_reference'))
        batch_op.drop_index(batch_op.f('ix_visitor_requests_external_session_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_requests_email'))
        batch_op.drop_index(batch_op.f('ix_visitor_requests_consent_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_requests_campus'))

    op.drop_table('visitor_requests')
    with op.batch_alter_table('newsletter_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_newsletter_subscriptions_email'))
        batch_op.drop_index(batch_op.f('ix_newsletter_subscriptions_consent_id'))

    op.drop_table('newsletter_subscriptions')
    with op.batch_alter_table('knowledge_gap_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_gap_questions_session_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_gap_questions_gap_id'))

    op.drop_table('knowledge_gap_questions')
    with op.batch_alter_table('knowledge_gap_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_gap_answers_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_gap_answers_gap_id'))

    op.drop_table('knowledge_gap_answers')
    with op.batch_alter_table('knowledge_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_gaps_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_gaps_normalized_question'))
        batch_op.drop_index(batch_op.f('ix_knowledge_gaps_language'))
        batch_op.drop_index(batch_op.f('ix_knowledge_gaps_category'))

    op.drop_table('knowledge_gaps')
    with op.batch_alter_table('consent_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_grants_token_hash'))
        batch_op.drop_index(batch_op.f('ix_consent_grants_subject_hash'))
        batch_op.drop_index(batch_op.f('ix_consent_grants_session_id'))
        batch_op.drop_index(batch_op.f('ix_consent_grants_reference'))
        batch_op.drop_index(batch_op.f('ix_consent_grants_purpose'))

    op.drop_table('consent_grants')
    # ### end Alembic commands ###
