"""add_users_and_refresh_tokens

Revision ID: e61e6a8050dc
Revises: 4c6ab0d6e61a
Create Date: 2026-07-22 21:43:29.519612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61e6a8050dc'
down_revision: Union[str, Sequence[str], None] = '4c6ab0d6e61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
