
model_list:
  - model_name: gemini-3.5-flash-lite
    litellm_params:
      model: gemini/gemini-3.5-flash-lite
      api_key: os.environ/GOOGLE_API_KEY

litellm_settings:
  cache: true
  cache_params:
    type: redis
    host: redis
    port: 6379
